/**
* This file has been auto-generated by Airam.
*/
namespace Airam\Cache;

use Airam\Service\ApplicationService;
use function Airam\Commons\{path_join,randomId,class_use};
use function Airam\Template\Lib\{is_layout,is_template};

return <?=$code ?>;