<?php /** @var \Airam\Commons\Compiler\DataTokens $data */ ?>
/**
* This file has been auto-generated by Airam.
*/
<?php if(isset($data->namespaceName) && strlen($data->namespaceName)>0): ?>
    namespace <?= $data->namespaceName; ?>;
<?php endif; ?>

<?php foreach ($data->usages as $usage) : ?>
    use <?= $usage; ?>;
<?php endforeach; ?>

<?= $data->code; ?>